import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import {markdown,readJson,parseFrontMatter} from "../scripts/lib.mjs";
test("01 markdown escapes raw html",()=>assert.match(markdown("<script>alert(1)</script>"),/&lt;script&gt;/));
test("02 markdown renders safe links",()=>assert.match(markdown("[source](https://example.com)"),/<a href="https:\/\/example.com">source<\/a>/));
test("03 exact article count",()=>assert.equal(readJson("data/content-plan.json").filter(x=>x.type==="article").length,10));
test("04 exact blog count",()=>assert.equal(readJson("data/content-plan.json").filter(x=>x.type==="blog").length,10));
test("05 unique slugs",()=>{const p=readJson("data/content-plan.json");assert.equal(new Set(p.map(x=>x.slug)).size,p.length);});
test("06 public brand name",()=>assert.equal(readJson("data/site.json").name,"Wellness Signal"));
test("07 internal key",()=>assert.equal(readJson("data/site.json").internal_key,"WellSignal"));
test("08 domain",()=>assert.equal(readJson("data/site.json").url,"https://wellsignal.org"));
test("09 forest token",()=>assert.equal(readJson("data/site.json").colors.forest,"#1F6B4F"));
test("10 sage token",()=>assert.equal(readJson("data/site.json").colors.sage,"#A7C3AE"));
test("11 terracotta token",()=>assert.equal(readJson("data/site.json").colors.terracotta,"#C97B63"));
test("12 cream token",()=>assert.equal(readJson("data/site.json").colors.cream,"#F8F5EF"));
test("13 display font",()=>assert.equal(readJson("data/site.json").fonts.display,"Cormorant Garamond"));
test("14 body font",()=>assert.equal(readJson("data/site.json").fonts.body,"Source Sans 3"));
test("15 assets imported",()=>assert.equal(readJson("data/assets.json").length,5));
test("16 nonproduction noindex",()=>{const m=readJson("dist/build-manifest.json");assert.equal(m.indexable,false);assert.ok(["local","staging"].includes(m.environment));});
test("17 homepage latest research",()=>assert.ok(fs.readFileSync("dist/index.html","utf8").includes("Latest Research")));
test("18 drafts banner",()=>{const p=readJson("data/content-plan.json")[0];const h=fs.readFileSync("dist"+p.slug+"index.html","utf8");assert.ok(h.includes("Editorial draft"));assert.ok(h.includes("noindex,nofollow,noarchive"));});
test("19 research stages valid",()=>{for(const p of readJson("data/content-plan.json")){const r=readJson("content/research/"+p.id+".json");assert.ok(["scaffolded","researched","verified"].includes(r.status));}});
test("20 evidence review exists",()=>{for(const p of readJson("data/content-plan.json"))assert.ok(readJson("content/research/"+p.id+".json").evidence_review);});
test("21 home complete",()=>assert.equal(parseFrontMatter(fs.readFileSync("content/pages/home.md","utf8")).data.complete,true));
test("22 production approval false",()=>assert.equal(readJson("data/release.json").approvals.production,false));
test("23 brand clearance false",()=>assert.equal(readJson("data/release.json").approvals.brand_clearance_review,false));
