import fs from "node:fs";
import path from "node:path";
import { readJson, parseFrontMatter, markdown, escapeHtml, cleanSlug, canonical, listFiles } from "./lib.mjs";

const site=readJson("data/site.json"),nav=readJson("data/navigation.json"),plan=readJson("data/content-plan.json"),assets=readJson("data/assets.json");
const env=process.env.BUILD_ENV||"local";
if(!["local","staging","production"].includes(env))throw new Error("Invalid BUILD_ENV");
if(env==="production"&&process.env.SITE_URL&&process.env.SITE_URL!==site.url)throw new Error("SITE_URL does not match data/site.json");
const indexable=env==="production"&&site.launch_status==="ready",dist="dist";
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});fs.mkdirSync(path.join(dist,"styles"),{recursive:true});fs.mkdirSync(path.join(dist,"scripts"),{recursive:true});
fs.copyFileSync("src/styles/main.css",path.join(dist,"styles/main.css"));fs.copyFileSync("src/scripts/main.js",path.join(dist,"scripts/main.js"));fs.copyFileSync("src/static/.htaccess",path.join(dist,".htaccess"));
for(const a of assets.filter(x=>x.deploy!==false)){if(!fs.existsSync(a.path))continue;const d=path.join(dist,a.path);fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(a.path,d);}
const pages=listFiles("content/pages",".md").map(file=>{const p=parseFrontMatter(fs.readFileSync(file,"utf8"));return {...p.data,body:p.body,file,draft:false};});
const posts=listFiles("content/posts",".md").map(file=>{const p=parseFrontMatter(fs.readFileSync(file,"utf8"));return {...p.data,body:p.body,file,draft:p.data.draft!==false};});
const builtPosts=env==="production"?posts.filter(p=>!p.draft):posts;
const primary=nav.primary.map(x=>'<li><a href="'+x.href+'">'+escapeHtml(x.label)+"</a></li>").join(""),footer=nav.footer.map(x=>'<a href="'+x.href+'">'+escapeHtml(x.label)+"</a>").join(" · ");
function data(item,kind){const url=canonical(site.url,item.slug);if(kind==="post")return {"@context":"https://schema.org","@type":item.type==="blog"?"BlogPosting":"Article",headline:item.title,url,description:item.description};if(item.template==="home")return {"@context":"https://schema.org","@graph":[{"@type":"Organization",name:site.name,url:site.url},{"@type":"WebSite",name:site.name,url:site.url}]};return {"@context":"https://schema.org","@type":item.type==="hub"?"CollectionPage":"WebPage",name:item.title,url,description:item.description};}
function shell(item,inner,kind="page"){const robots=indexable&&!item.noindex&&!item.draft?"index,follow":"noindex,nofollow,noarchive",url=canonical(site.url,item.slug),json=JSON.stringify(data(item,kind)).replace(/</g,"\\u003c"),banner=item.draft&&env!=="production"?'<div class="draft-banner">Editorial draft. Not for publication.</div>':"";return ["<!doctype html>",'<html lang="en"><head>','<meta charset="utf-8">','<meta name="viewport" content="width=device-width,initial-scale=1">',"<title>"+escapeHtml(item.seo_title||item.title)+"</title>",'<meta name="description" content="'+escapeHtml(item.description||"")+'">','<meta name="robots" content="'+robots+'">','<link rel="canonical" href="'+url+'">','<meta property="og:title" content="'+escapeHtml(item.title)+'">','<meta property="og:description" content="'+escapeHtml(item.description||"")+'">','<meta property="og:url" content="'+url+'">','<meta property="og:type" content="'+(kind==="post"?"article":"website")+'">','<link rel="stylesheet" href="/styles/main.css">','<script type="application/ld+json">'+json+"</script>","</head><body>",'<a class="skip-link" href="#main">Skip to content</a>',banner,'<header class="site-header"><nav class="nav" aria-label="Primary">','<a class="brand" href="/">Wellness Signal</a>','<button class="nav-toggle" data-nav-toggle aria-expanded="false">Menu</button>','<ul class="nav-list" data-nav-list>'+primary+"</ul>","</nav></header>",'<main id="main">'+inner+"</main>",'<footer class="site-footer"><div class="wrap"><strong>Wellness Signal</strong><p>'+escapeHtml(site.tagline)+"</p><p>"+footer+"</p></div></footer>",'<script src="/scripts/main.js" defer></script>',"</body></html>"].join("");}
function write(slug,html){const dir=path.join(dist,cleanSlug(slug).replace(/^\//,""));fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,"index.html"),html);}
for(const p of pages){let extra="";if(p.template==="home"){const cards=builtPosts.slice(0,6).map(x=>'<article class="card"><div class="eyebrow">'+escapeHtml(x.type)+'</div><h3><a href="'+x.slug+'">'+escapeHtml(x.title)+"</a></h3></article>").join("");extra='<section class="wrap"><h2>Latest Research</h2><div class="grid">'+(cards||'<p class="muted">Research is in editorial review.</p>')+"</div></section>";}else if(p.type==="hub"){const matches=builtPosts.filter(x=>x.slug.startsWith(p.slug)),label=env==="production"?"Published Research":"Research Pipeline",cards=matches.map(x=>'<article class="card"><h3><a href="'+x.slug+'">'+escapeHtml(x.title)+"</a></h3></article>").join("");extra='<section class="wrap"><h2>'+label+'</h2><div class="grid">'+(cards||'<p class="muted">No published research is available in this section yet.</p>')+"</div></section>";}write(p.slug,shell(p,'<article class="wrap prose">'+markdown(p.body)+"</article>"+extra));}
for(const p of builtPosts)write(p.slug,shell(p,'<article class="wrap prose"><div class="eyebrow">'+escapeHtml(p.type)+"</div>"+markdown(p.body)+"</article>","post"));
const items=[...pages.filter(x=>!x.noindex),...builtPosts].filter(x=>!(env==="production"&&x.draft));fs.writeFileSync(path.join(dist,"sitemap.xml"),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+items.map(x=>"<url><loc>"+canonical(site.url,x.slug)+"</loc></url>").join("")+"</urlset>");
const feedPosts=builtPosts.filter(x=>!x.draft&&x.published);fs.writeFileSync(path.join(dist,"feed.xml"),'<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom"><title>'+escapeHtml(site.name)+"</title><id>"+site.url+'</id><link href="'+site.url+'/feed.xml" rel="self"/>'+feedPosts.map(x=>"<entry><title>"+escapeHtml(x.title)+"</title><id>"+canonical(site.url,x.slug)+'</id><link href="'+canonical(site.url,x.slug)+'"/><updated>'+escapeHtml(x.modified||x.published)+"</updated></entry>").join("")+"</feed>");
fs.writeFileSync(path.join(dist,"robots.txt"),indexable?"User-agent: *\nAllow: /\nSitemap: "+site.url+"/sitemap.xml\n":"User-agent: *\nDisallow: /\n");
fs.writeFileSync(path.join(dist,"build-manifest.json"),JSON.stringify({environment:env,indexable,pages:pages.length,planItems:plan.length,postsBuilt:builtPosts.length},null,2));
console.log("Built Wellness Signal:",env,pages.length,"pages",builtPosts.length,"posts");
