import fs from "node:fs";import {readJson,parseFrontMatter,listFiles} from "./lib.mjs";
const site=readJson("data/site.json"),plan=readJson("data/content-plan.json"),assets=readJson("data/assets.json"),kill=readJson("data/ai-kill-list.json"),errors=[];
if(!site.url.startsWith("https://"))errors.push("Site URL must use HTTPS.");
if(plan.filter(x=>x.type==="article").length!==10)errors.push("Content plan must contain exactly 10 articles.");
if(plan.filter(x=>x.type==="blog").length!==10)errors.push("Content plan must contain exactly 10 blogs.");
if(new Set(plan.map(x=>x.id)).size!==plan.length)errors.push("Duplicate content IDs.");
if(new Set(plan.map(x=>x.slug)).size!==plan.length)errors.push("Duplicate content slugs.");
const ids=new Set(plan.map(x=>x.id));for(const p of plan){for(const id of p.internal_link_targets||[])if(!ids.has(id))errors.push("Unknown link target "+id+" in "+p.id);for(const key of ["id","type","title","primary_keyword","slug","hub","cluster","role"])if(!p[key])errors.push("Missing "+key+" in "+p.id);}
for(const a of assets){for(const k of ["path","width","height","role","alt"])if(a[k]===undefined||a[k]===null||a[k]==="")errors.push("Asset incomplete: "+(a.path||"unknown")+" "+k);if(a.deploy!==false&&!fs.existsSync(a.path))errors.push("Asset file missing: "+a.path);}
for(const p of plan){const postPath="content/posts/"+p.id+".md",researchPath="content/research/"+p.id+".json";if(!fs.existsSync(postPath)){errors.push("Missing post "+p.id);continue}if(!fs.existsSync(researchPath)){errors.push("Missing research "+p.id);continue}const parsed=parseFrontMatter(fs.readFileSync(postPath,"utf8")),d=parsed.data,body=parsed.body,r=JSON.parse(fs.readFileSync(researchPath,"utf8"));for(const [k,v] of [["content_id",p.id],["slug",p.slug],["type",p.type],["primary_keyword",p.primary_keyword]])if(d[k]!==v)errors.push(p.id+" post "+k+" mismatch");if(r.content_id!==p.id||r.slug!==p.slug)errors.push(p.id+" research mapping mismatch");if(r.required_seo_tool!==site.required_seo_tool)errors.push(p.id+" missing required SEO tool");if(d.draft===false){if(r.status!=="verified")errors.push(p.id+" published without verified research");if(r.fact_check?.status!=="approved")errors.push(p.id+" fact check not approved");if(r.evidence_review?.status!=="approved")errors.push(p.id+" evidence review not approved");if(r.qa?.status!=="approved")errors.push(p.id+" QA not approved");const lower=body.toLowerCase();for(const phrase of kill)if(lower.includes(String(phrase).toLowerCase()))errors.push(p.id+" contains banned phrase: "+phrase);const internal=(body.match(/\]\(\//g)||[]).length,external=(body.match(/\]\(https:\/\//g)||[]).length;if(internal<2)errors.push(p.id+" needs at least 2 internal links");if(external<3)errors.push(p.id+" needs at least 3 external links");}}
for(const file of listFiles("dist",".html")){const html=fs.readFileSync(file,"utf8");for(const token of ["<title>","meta name=\"description\"","meta name=\"robots\"","rel=\"canonical\"","application/ld+json","<h1"])if(!html.includes(token))errors.push(file+" missing "+token);if(html.includes("—"))errors.push(file+" contains em dash");}
if(errors.length){console.error(errors.join("\n"));process.exit(1)}console.log("Repository QA passed.");
