import fs from "node:fs";import path from "node:path";
export const root=process.cwd();
export const readJson=(p)=>JSON.parse(fs.readFileSync(path.join(root,p),"utf8"));
export const escapeHtml=(s="")=>String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
export const cleanSlug=(s)=>{let x=String(s||"/").trim();if(!x.startsWith("/"))x="/"+x;if(!x.endsWith("/"))x+="/";return x.replace(/\/+/g,"/");};
export const canonical=(base,slug)=>base.replace(/\/$/,"")+cleanSlug(slug);
export function parseFrontMatter(text){if(!text.startsWith("---\n"))return {data:{},body:text};const end=text.indexOf("\n---\n",4);if(end<0)return {data:{},body:text};const head=text.slice(4,end),body=text.slice(end+5);const data={};for(const line of head.split(/\r?\n/)){const i=line.indexOf(":");if(i<0)continue;const k=line.slice(0,i).trim(),raw=line.slice(i+1).trim();let v=raw;if(raw==="true")v=true;else if(raw==="false")v=false;else if(raw==="null")v=null;else if(/^-?\d+(\.\d+)?$/.test(raw))v=Number(raw);else if((raw.startsWith("[")&&raw.endsWith("]"))||(raw.startsWith("{")&&raw.endsWith("}"))){try{v=JSON.parse(raw)}catch{v=raw}}data[k]=v;}return {data,body};}
export function inline(text){let s=escapeHtml(text);s=s.replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\`([^\`]+)\`/g,"<code>$1</code>");s=s.replace(/\[([^\]]+)\]\((https:\/\/[^\s)]+|\/[^\s)]*)\)/g,'<a href="$2">$1</a>');return s;}
export function markdown(md){const lines=md.split(/\r?\n/);let out="",list=null;const close=()=>{if(list){out+=`</${list}>`;list=null;}};for(const raw of lines){const l=raw.trimEnd();let m;if((m=l.match(/^(#{1,3})\s+(.+)/))){close();const n=m[1].length;out+=`<h${n}>${inline(m[2])}</h${n}>`;}else if((m=l.match(/^[-*]\s+(.+)/))){if(list!=="ul"){close();list="ul";out+="<ul>";}out+=`<li>${inline(m[1])}</li>`;}else if((m=l.match(/^\d+\.\s+(.+)/))){if(list!=="ol"){close();list="ol";out+="<ol>";}out+=`<li>${inline(m[1])}</li>`;}else if(!l.trim()){close();}else{close();out+=`<p>${inline(l)}</p>`;}}close();return out;}
export const listFiles=(dir,ext)=>{const abs=path.join(root,dir);if(!fs.existsSync(abs))return[];return fs.readdirSync(abs,{withFileTypes:true}).flatMap(e=>e.isDirectory()?listFiles(path.join(dir,e.name),ext):[path.join(dir,e.name)]).filter(p=>!ext||p.endsWith(ext));};
